name: build - web
on:
  pull_request:
    paths:
      - packages/react-components/**
      - apps/web/**
    types: [opened, synchronize]

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install --filter=web

      - name: Build
        run: pnpm run build:web
