name: deploy - api
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/deploy-api.yaml
      - apps/api/**

env:
  BEANSTALK_APPLICATION_NAME: i-review
  BEANSTALK_ENVIRONMENT_NAME: I-review-env

jobs:
  deply:
    runs-on: ubuntu-latest
    environment: Production - api
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install --filter=api

      - name: Build
        run: pnpm run build:api

      - name: Pack
        run: |
          mkdir source
          cp -rf apps/api/ncc/. source/
          cp apps/api/Dockerfile source/Dockerfile
          cp apps/api/fly.toml source/fly.toml
          zip -r -y -q ${{github.run_id}}.zip source

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: deploy-files
          path: ${{github.run_id}}.zip
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy To Flyio
        run: |
          cd source
          ls -al
          pwd
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
