name: deploy - web
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/deploy-web.yaml
      - packages/react-components/**
      - apps/web/**

env:
  API_ORIGIN: ${{ secrets.API_ORIGIN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production - web
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install --filter=web...

      - name: Build
        run: pnpm run build:web

      - name: Pack
        run: |
          mkdir source
          cp -r apps/web/.next/standalone/. ./source
          cp -r apps/web/.next/static ./source
          cp -r apps/web/public ./source
          cp apps/web/Dockerfile source/Dockerfile
          cp apps/web/fly.toml source/fly.toml
          cd source
          zip -r ../${{github.run_id}}.zip .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: deploy-files
          path: ${{github.run_id}}.zip

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy To Flyio
        run: |
          ls -al
          pwd
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
