name: deploy - api
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-api.yaml
      - apps/api/**

env:
  BEANSTALK_APPLICATION_NAME: i-review
  BEANSTALK_ENVIRONMENT_NAME: I-review-env

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |  
          npm install --workspaces=false
          npm install --workspace=api

      - name: Build
        run: |
          npm run build:api
          npm uninstall turbo

      - name: Pack
        run: |
          zip -r ${{github.run_id}}.zip .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: deploy-files
          path: ${{github.run_id}}.zip

  deploy:
    runs-on: ubuntu-latest
    environment: Production - api
    needs: build

    steps:
      - uses: actions/download-artifact@v4.1.8
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy
        run: |
          aws s3 cp "deploy-files/${{github.run_id}}.zip" s3://elasticbeanstalk-ap-northeast-2-${{ secrets.AWS_ACCOUNT_ID }}/
          aws elasticbeanstalk create-application-version --application-name $BEANSTALK_APPLICATION_NAME --version-label ${{github.run_id}} --description ${{github.run_id}} --source-bundle S3Bucket="elasticbeanstalk-ap-northeast-2-${{ secrets.AWS_ACCOUNT_ID }}",S3Key="${{github.run_id}}.zip"
          aws elasticbeanstalk update-environment --application-name $BEANSTALK_APPLICATION_NAME --environment-name $BEANSTALK_ENVIRONMENT_NAME --version-label ${{github.run_id}}
          aws elasticbeanstalk wait environment-updated --application-name $BEANSTALK_APPLICATION_NAME --environment-name $BEANSTALK_ENVIRONMENT_NAME
